"""initial schema

Revision ID: c1c5a53994c0
Revises:
Create Date: 2026-09-02 21:28:49.405252
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = 'c1c5a53994c0'
down_revision: str | None = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('window_hours', sa.Integer(), nullable=False),
    sa.Column('allowed_platforms', sa.String(length=200), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('window_hours > 0', name=op.f('ck_campaigns_window_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_status'), ['status'], unique=False)

    op.create_table('campaign_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_assets_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_assets')),
    sa.UniqueConstraint('campaign_id', 'sha256', name='uq_asset_per_campaign')
    )
    with op.batch_alter_table('campaign_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_assets_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_assets_sha256'), ['sha256'], unique=False)

    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('user_ref', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_enrollments_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollments')),
    sa.UniqueConstraint('campaign_id', 'user_ref', name='uq_user_per_campaign')
    )
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollments_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_user_ref'), ['user_ref'], unique=False)

    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('post_url', sa.String(length=1000), nullable=False),
    sa.Column('declared_platform', sa.String(length=30), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('resolved_platform', sa.String(length=30), nullable=True),
    sa.Column('post_id', sa.String(length=200), nullable=True),
    sa.Column('canonical_url', sa.String(length=1000), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('age_seconds', sa.Integer(), nullable=True),
    sa.Column('within_window', sa.Boolean(), nullable=True),
    sa.Column('matched_asset_id', sa.Integer(), nullable=True),
    sa.Column('image_score', sa.Integer(), nullable=True),
    sa.Column('image_verdict', sa.String(length=20), nullable=True),
    sa.Column('dedupe_key', sa.String(length=250), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['campaign_assets.id'], name=op.f('fk_submissions_asset_id_campaign_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_submissions_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_submissions_enrollment_id_enrollments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_asset_id'], ['campaign_assets.id'], name=op.f('fk_submissions_matched_asset_id_campaign_assets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submissions')),
    sa.UniqueConstraint('dedupe_key', name='uq_live_post')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index('ix_submission_queue', ['status', 'next_attempt_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_enrollment_id'), ['enrollment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_status'), ['status'], unique=False)

    op.create_table('verification_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=True),
    sa.Column('checked_asset_id', sa.Integer(), nullable=True),
    sa.Column('checked_asset_sha256', sa.String(length=64), nullable=True),
    sa.Column('assets_tried', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('age_seconds', sa.Integer(), nullable=True),
    sa.Column('window_hours', sa.Integer(), nullable=True),
    sa.Column('within_window', sa.Boolean(), nullable=True),
    sa.Column('image_verdict', sa.String(length=20), nullable=True),
    sa.Column('image_score', sa.Integer(), nullable=True),
    sa.Column('image_present', sa.Boolean(), nullable=True),
    sa.Column('engine_response', sa.JSON(), nullable=True),
    sa.Column('engine_status', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('evidence_path', sa.String(length=500), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name=op.f('fk_verification_records_submission_id_submissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_records')),
    sa.UniqueConstraint('submission_id', 'attempt', name='uq_attempt')
    )
    with op.batch_alter_table('verification_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_records_submission_id'), ['submission_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_records_submission_id'))

    op.drop_table('verification_records')
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submissions_status'))
        batch_op.drop_index(batch_op.f('ix_submissions_enrollment_id'))
        batch_op.drop_index(batch_op.f('ix_submissions_created_at'))
        batch_op.drop_index(batch_op.f('ix_submissions_campaign_id'))
        batch_op.drop_index('ix_submission_queue')

    op.drop_table('submissions')
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollments_user_ref'))
        batch_op.drop_index(batch_op.f('ix_enrollments_status'))
        batch_op.drop_index(batch_op.f('ix_enrollments_campaign_id'))

    op.drop_table('enrollments')
    with op.batch_alter_table('campaign_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_assets_sha256'))
        batch_op.drop_index(batch_op.f('ix_campaign_assets_campaign_id'))

    op.drop_table('campaign_assets')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_status'))

    op.drop_table('campaigns')
    # ### end Alembic commands ###
